### ISSUE TITLE
feature request: functional in group field

### ISSUE THREAD

**Issue by clebuchegger** [rubengc/cmb2-field-ajax-search#1]
hi,
really great plugin, do you think it's possible to make it functional in a group field?
thx!

**Comment by rubengc** [comment]
Of course!

What happen if you add this field in a group field?

I need to investigate how group fields work, for sure I need to initialize again the search in some specific js event triggered from CMB2

**Comment by rubengc** [comment]
I have ready v1.0.1 with support from CSS and JS for repeatable groups and widgets area and some bug fixes

On test It a bit more I will commit changes today!

**Comment by rubengc** [comment]
Fixed ^^
